### ISSUE TITLE
Usage instructions don't work without calling python

### ISSUE THREAD

**Issue by msschwartz21** [johndoe31415/biblint#1]
After cloning the repo, I was unable to use the program by running `./biblint references.bib`. I ultimately needed to call `python biblint references.bib`.

**Comment by johndoe31415** [comment]
Hey and thanks for trying out biblint. You're the first person to ever report using it apart from me so I'm super psyched :-D

Regarding the issue, were the permissions wrong? Or what kind of error did you receive? Are you on a Mac? I think I might need to replace the shebang by `/usr/bin/env`, that should work across all architectures.

Will hopefully fix this issue tonight.

**Comment by johndoe31415** [comment]
Think this should fix the issue for you. If it still doesn't work, please report back and reopen. Cheers!
